return {
	"kevinhwang91/nvim-bqf",
	event = "VeryLazy",
	opts = {
		auto_resize_height = false,
		filter = {
			fzf = {
				action_for = {
					["ctrl-c"] = "closeall",
					["ctrl-q"] = "signtoggle",
					["ctrl-t"] = "tabedit",
					["ctrl-v"] = "vsplit",
					["ctrl-x"] = "split",
				},
				extra_opts = { "--bind", "ctrl-o:toggle-all" },
			},
		},
		func_map = {
			filter = "F",
			filterr = "f",
			fzffilter = "/",
			nexthist = "l",
			prevhist = "h",
			nextfile = "<C-n>",
			prevfile = "<C-p>",
			ptoggleauto = "P",
			ptoggleitem = "p",
			open = "<CR>",
			openc = "o",
			split = "s",
			vsplit = "v",
			stogglevm = "<Tab>",

			drop = "O",
			lastleave = "'\"",
			pscrolldown = "<C-f>",
			pscrollorig = "zo",
			pscrollup = "<C-b>",
			ptogglemode = "zp",
			sclear = "z<Tab>",
			-- stogglebuf = "<Tab>",
			stoggledown = "<space>",
			stoggleup = "<S-Tab>",
			tab = "t",
			tabb = "T",
			tabc = "<C-t>",
			tabdrop = "",
		},
		magic_window = true,
		preview = {
			auto_preview = false,
			border = "rounded",
			buf_label = true,
			delay_syntax = 50,
			show_scroll_bar = true,
			show_title = true,
			win_height = 15,
			win_vheight = 15,
			winblend = 12,
			wrap = false,
		},
		previous_winid_ft_skip = {},
	},
}
